kind: Deployment
apiVersion: apps/v1
metadata:
  name: sim-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sim-portfolio
  template:
    metadata:
      labels:
        app: sim-portfolio
    spec:
      containers:
      - name: sim-portfolio
        image: bamsham/sim-portfolio
        ports:
        - name: web
          containerPort: 80
